apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
  labels:
    app: fastapi-api
spec:
  template:
    spec:
      containers:
        - name: fastapi-api
          command: ["/bin/sh", "-ec", "sleep infinity"]
