# API
apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: api
build:
  artifacts:
  - image: docker-registry.local:5000/skaffold-monorepo-toy-api
    context: services/fastapi-api
    sync:
      infer:
        - 'app'
    docker:
      dockerfile: Dockerfile
    hooks:
      after:
        - command: [ "sh", "-c", "./scripts/skaffold/dump-poetry-lock.sh" ]
          os: [ darwin, linux ]
  local:
    useBuildkit: true
    push: true
deploy:
  kustomize:
    paths:
      - services/fastapi-api/overlay/development
      - infra/postgres/overlay/development-api
    hooks:
      after:
        - host:
            command: [ "sh", "-c", "./scripts/skaffold/post-deploy.sh" ]

portForward:
- resourceType: service
  namespace: default
  resourceName: dev-fastapi-api
  port: 8000
- resourceType: service
  namespace: default
  resourceName: dev-api-postgres
  port: 5432

profiles:
  - name: dev-sleep
    patches:
      - op: replace
        path: /deploy/kustomize/paths/0
        value: services/fastapi-api/overlay/development-sleep
  - name: no-postgres
    patches:
      - op: delete
        path: /deploy/kustomize/paths/1
