version: '3'

vars:
  PROJECT_NAME: skaffold-monorepo-toy
  BASE_DIR:
    sh: git rev-parse --show-toplevel
  DEVTOOLS_DIR:
    sh: echo "{{.BASE_DIR}}/tools/devtools"

tasks:
  dev:setup:
    desc: Setup dev environment (you only need this once!)
    cmds:
      - PROJECT_NAME={{.PROJECT_NAME}} BASE_DIR={{.BASE_DIR}} scripts/dev/setup.sh

  dev:delete:
    desc: Delete dev environment - once you ran this, you will need to setup again should you want to develop again.
    cmds:
      - PROJECT_NAME={{.PROJECT_NAME}} BASE_DIR={{.BASE_DIR}} scripts/dev/delete.sh

  dev:start:
    desc: Start dev environment
    cmds:
      - PROJECT_NAME={{.PROJECT_NAME}} BASE_DIR={{.BASE_DIR}} scripts/dev/start.sh

  dev:teardown:
    desc: Teardown dev environment
    cmds:
      - PROJECT_NAME={{.PROJECT_NAME}} BASE_DIR={{.BASE_DIR}} scripts/dev/teardown.sh

  dev:api-postgres:
    desc: Connect to API's postgres with psql
    cmds:
      - POD_PATTERN="dev-api-postgres-.*" {{.DEVTOOLS_DIR}}/pod-exec.sh psql -U some_user -d some_db
