apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-api-config
  labels:
    app: fastapi-api
data:
  SECRET_KEY: 558BGdwZAgW3URgS228BGdwZAgW3URgS
  SENTRY_DSN: ""
  POSTGRES_SERVER: dev-api-postgres
  POSTGRES_USER: some_user
  POSTGRES_PASSWORD: somepasswordhere
  POSTGRES_DB: some_db
