apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-api
  labels:
    app: fastapi-api
spec:
  template:
    spec:
      containers:
        - name: fastapi-api
          volumeMounts:
            - mountPath: /poetry.lock
              name: poetry-lock
            - mountPath: /pyproject.toml
              name: pyproject-toml
            - mountPath: /app/
              name: fastapi-api-app
      volumes:
        - name: poetry-lock
          hostPath:
            path: /mnt/repo/services/fastapi-api/poetry.lock
            type: File
        - name: fastapi-api-app
          hostPath:
            path: /mnt/repo/services/fastapi-api/app
            type: Directory
        - name: pyproject-toml
          hostPath:
            path: /mnt/repo/services/fastapi-api/pyproject.toml
            type: File
